[package]
name = "zeron-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["native"]
native = ["dep:cpal"]
aec = ["dep:webrtc-audio-processing"]

[dependencies]
zeron-proto.workspace = true
base64.workspace = true
crossbeam-queue.workspace = true
cpal = { workspace = true, optional = true }
webrtc-audio-processing = { workspace = true, optional = true }
thiserror.workspace = true
